### ISSUE TITLE
Enhancement suggestion: add "open all modified documents" too.

### ISSUE THREAD

**Issue by Git-GT** [markiewb/nb-git-close-unmodified-documents#4]
Hi Markiewb,
thanks for this other very useful plugin!

I have a suggestion for an enhancement. 
Could you add also a feature to open all the modified documents? 
It would be useful for example to have a last look of the changes before a commit.

I guess that a problem arises when there are many modified files and open them all could be problematic. To avoid this you could add an option to specify a limit so that in case the command execution requires to open more than that number of files it displays an alert to advice the user and opens only the first modified files.

**Comment by markiewb** [comment]
@Gittino: Won't fix. 

Please use "Team|Show Changes". This opens a window with all the changed files (make sure that you select the project node or the top most node in the repo before invoking the action). All changed files will be listed. You can press CTRL-A to select them all. In the context menu invoke "Open" to "open all the modified documents".

Thank you for your interest and your praise!
